export const COLLECTION_STORAGE_ENTRY_PREFIX = 'ci';
export const LIST_QUERY_ITEM_STORAGE_ENTRY_PREFIX = 'li';
export const LIST_QUERY_QUERY_STORAGE_ENTRY_PREFIX = 'lq';
export const OFFLINE_QUEUE_STORAGE_ENTRY_PREFIX = 'oq';
export const OFFLINE_CONFLICT_STORAGE_ENTRY_PREFIX = 'oc';
export const OFFLINE_ENTITY_STORAGE_ENTRY_PREFIX = 'oe';
