import { createLoggerStore } from '@ls-stack/utils/testUtils';
import { act, cleanup, renderHook } from '@testing-library/react';
import '@testing-library/react/dont-cleanup-after-each';
import {
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  expect,
  test,
  vi,
} from 'vitest';
import {
  createListQueryStoreTestEnv,
  type Tables,
} from '../mocks/listQueryStoreTestEnv';
import { TEST_INITIAL_TIME } from '../mocks/testEnvUtils';
import { range } from '../utils/genericTestUtils';
import { advanceTime, flushAllTimers } from '../utils/listQueryHooksTestUtils';

const initialServerData: Tables = {
  users: range(1, 5).map((id) => ({ id, name: `User ${id}` })),
  products: range(1, 50).map((id) => ({ id, name: `Product ${id}` })),
  orders: range(1, 50).map((id) => ({ id, name: `Order ${id}` })),
};

beforeAll(() => {
  vi.useFakeTimers();
});

beforeEach(() => {
  vi.setSystemTime(TEST_INITIAL_TIME);
});

afterEach(() => {
  vi.runOnlyPendingTimers();
});

afterAll(() => {
  cleanup();
});

type TestEnv = ReturnType<typeof createListQueryStoreTestEnv>;

function getUsersNamesFromState(env: TestEnv): string[] {
  const usersQuery = env.apiStore.getQueryState({ tableId: 'users' });
  if (!usersQuery) return [];

  return usersQuery.items.flatMap((itemKey) => {
    const item = env.apiStore.store.state.items[itemKey];
    return item ? [item.name] : [];
  });
}

async function addItemWithIdGeneratedByServer(
  env: TestEnv,
  tableId: string,
  name: string,
  {
    revalidate,
    duration,
    triggerRTU,
  }: {
    revalidate?: boolean;
    duration?: number;
    triggerRTU?: boolean;
  } = {},
) {
  return env.apiStore.performMutation(`${tableId}||?`, {
    mutation: async () => {
      return env.serverTable.addItemWithAutoGeneratedKey(
        tableId,
        (id) => ({ id, name }),
        {
          duration,
          triggerRTUEvent: triggerRTU,
        },
  );
    },
    onSuccess: ({ itemId, data }) => {
      env.apiStore.addItemToState(itemId, data);
    },
    revalidateOnSuccess: revalidate ? 'queries' : false,
    getRelatedQueries: (payload) => payload.tableId === tableId,
    });
}

async function addItemWithIdGeneratedByClient(
  env: TestEnv,
  tableId: string,
  userId: string,
  name: string,
  {
    revalidate,
    duration,
    triggerRTU,
  }: {
    revalidate?: boolean;
    duration?: number;
    triggerRTU?: boolean;
  } = {},
) {
  const id = `${tableId}||${userId}`;
  const newRow = { id: Number(userId), name };

  return env.apiStore.performMutation(id, {
    optimisticUpdate: () => {
      env.apiStore.addItemToState(id, newRow);
    },
    mutation: async () => {
      await env.serverTable.addItem(id, newRow, {
        duration,
        triggerRTUEvent: triggerRTU,
      });

      return newRow;
    },
    revalidateOnSuccess: revalidate,
    getRelatedQueries: (payload) => payload.tableId === tableId,
    });
}

async function deleteItem(
  env: TestEnv,
  tableId: string,
  itemId: number,
  {
    revalidate,
    duration,
    optimisticUpdate,
    triggerRTU,
  }: {
    revalidate?: boolean;
    optimisticUpdate?: boolean;
    duration?: number;
    triggerRTU?: boolean;
  } = {},
) {
  const id = `${tableId}||${itemId}`;

  return env.apiStore.performMutation(id, {
    optimisticUpdate:
      optimisticUpdate ?
        () => {
          env.apiStore.deleteItemState(id);
  }
      : undefined,
    mutation: async () => {
      await env.serverTable.deleteItem(id, {
        duration,
        triggerRTUEvent: triggerRTU,
      });

      return { deletedItemId: id };
    },
    revalidateOnSuccess: revalidate ? 'queries' : false,
    getRelatedQueries: (payload) => payload.tableId === tableId,
    });
}

test('user updating the name of a record', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users', 'products'] } },
  });

  const renders = createLoggerStore();

  renderHook(() => {
    const { data, status } = env.apiStore.useItem('users||1', {
      disableRefetchOnMount: true,
    });

    renders.add({ status, data });
  });

  function setName(name: string, duration: number) {
    act(() => {
      void env.performClientItemUpdateAction(
        'users||1',
        { name },
        {
          withOptimisticUpdate: true,
          withRevalidation: true,
      duration,
        },
      );
    });
  }

  setName('', 530);

  expect(env.apiStore.getItemState('users||1')).toMatchObject({ name: '' });

  await advanceTime(263);
  setName('T', 662);

  await advanceTime(263);
  setName('Ty', 560);

  await advanceTime(300);
  setName('Typ', 560);

  await advanceTime(226);
  setName('Type', 523);

  await flushAllTimers();

  expect(env.apiStore.getItemState('users||1')).toMatchObject({ name: 'Type' });
  expect(env.serverTable.numOfFinishedFetches).toBe(1);
  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: success ⋅ data: {id:1, name:User 1}
    -> status: success ⋅ data: {id:1, name:''}
    -> status: success ⋅ data: {id:1, name:T}
    -> status: success ⋅ data: {id:1, name:Ty}
    -> status: success ⋅ data: {id:1, name:Typ}
    -> status: success ⋅ data: {id:1, name:Type}
    "
  `);
});

test('user updating the name of a record, but a RTU is received for a table while the update is in progress', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users', 'products'] } },
    usesRealTimeUpdates: true,
    });

  const renders = createLoggerStore();

    renderHook(() => {
    const { data, status } = env.apiStore.useItem('users||1', {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
      });

      renders.add({ status, data });
    });

  act(() => {
    void env.performClientItemUpdateAction(
      'users||1',
      { name: 'newName' },
      {
        withOptimisticUpdate: true,
        withRevalidation: true,
      duration: 400,
      },
    );
    });

  await advanceTime(350);

  act(() => {
    env.serverTable.setItem(
      'users||1',
      { id: 1, name: 'RTU' },
      { triggerRTUEvent: true },
    );
    });

  await flushAllTimers();

  expect(env.apiStore.getItemState('users||1')).toMatchObject({
    name: 'RTU',
  });
  expect(env.serverTable.numOfFinishedFetches).toBeGreaterThanOrEqual(1);
  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: success ⋅ data: {id:1, name:User 1}
    -> status: success ⋅ data: {id:1, name:newName}
    -> status: refetching ⋅ data: {id:1, name:newName}
    -> status: success ⋅ data: {id:1, name:RTU}
    "
  `);
});

test('creation mutation with id generated by server', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users'] } },
  });

  const renders = createLoggerStore({ arrays: 'all' });

  renderHook(() => {
    const { items, status } = env.apiStore.useListQuery(
      { tableId: 'users' },
      {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
        itemSelector(data) {
          return data;
        },
      },
    );

    renders.add({ status, items });
  });

  act(() => {
    void addItemWithIdGeneratedByServer(env, 'users', 'newUser', {
    revalidate: true,
  });
  });

  await flushAllTimers();

  expect(env.serverTable.numOfFinishedFetches).toBe(1);
  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    ┌─
    ⋅ status: success
    ⋅ items: [{id:1, name:User 1}, {id:2, name:User 2}, {id:3, name:User 3}, {id:4, name:User 4}, {id:5, name:User 5}]
    └─
    ┌─
    ⋅ status: refetching
    ⋅ items: [{id:1, name:User 1}, {id:2, name:User 2}, {id:3, name:User 3}, {id:4, name:User 4}, {id:5, name:User 5}]
    └─
    ┌─
    ⋅ status: success
    ⋅ items: [{id:1, name:User 1}, {id:2, name:User 2}, {id:3, name:User 3}, {id:4, name:User 4}, {id:5, name:User 5}, {id:6, name:newUser}]
    └─
    "
  `);
});

test('creation mutation with id generated by client', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users'] } },
  });

  const queryRenders = createLoggerStore({ arrays: 'all' });

  renderHook(() => {
    const { items, status } = env.apiStore.useListQuery(
      { tableId: 'users' },
      {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
        itemSelector(data) {
          return data;
        },
      },
    );

    queryRenders.add({ status, items });
  });

  act(() => {
    void addItemWithIdGeneratedByClient(env, 'users', '7', 'newUser', {
    revalidate: true,
    });
  });

  await advanceTime(10);

  const mountWithItemRenders = createLoggerStore();

  renderHook(() => {
    const { data, status } = env.apiStore.useItem('users||7', {
      returnRefetchingStatus: true,
    });

    mountWithItemRenders.add({ status, data });
  });

  await flushAllTimers();

  expect(env.serverTable.numOfFinishedFetches).toBe(2);
  expect(queryRenders.snapshot).toMatchInlineSnapshot(`
    "
    ┌─
    ⋅ status: success
    ⋅ items: [{id:1, name:User 1}, {id:2, name:User 2}, {id:3, name:User 3}, {id:4, name:User 4}, {id:5, name:User 5}]
    └─
    ┌─
    ⋅ status: refetching
    ⋅ items: [{id:1, name:User 1}, {id:2, name:User 2}, {id:3, name:User 3}, {id:4, name:User 4}, {id:5, name:User 5}]
    └─
    ┌─
    ⋅ status: success
    ⋅ items: [{id:1, name:User 1}, {id:2, name:User 2}, {id:3, name:User 3}, {id:4, name:User 4}, {id:5, name:User 5}, {id:7, name:newUser}]
    └─
    "
  `);
  expect(mountWithItemRenders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: success ⋅ data: {id:7, name:newUser}
    -> status: refetching ⋅ data: {id:7, name:newUser}
    -> status: success ⋅ data: {id:7, name:newUser}
    "
  `);
});

test('user change multiple records in sequence with RTU enabled', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users'] } },
    usesRealTimeUpdates: true,
    });

  const renders = createLoggerStore({ arrays: 'all' });

    renderHook(() => {
    const { items, status } = env.apiStore.useListQuery(
        { tableId: 'users' },
        {
          returnRefetchingStatus: true,
          disableRefetchOnMount: true,
          itemSelector(data) {
            return `${data.id}:${data.name}`;
          },
        },
      );

      renders.add({ status, items });
    });

    function updateName(itemId: number, newName: string) {
    act(() => {
      void env.performClientItemUpdateAction(
        `users||${itemId}`,
        { name: newName },
        {
          withRevalidation: false,
          withOptimisticUpdate: true,
          triggerRTU: true,
          duration: 400,
        },
      );
      });
    }

    updateName(1, '✅');
  await advanceTime(200);

    updateName(2, '❌');
  await advanceTime(250);

    updateName(3, '✅');
  await advanceTime(230);

    updateName(4, '❌');
  await advanceTime(250);

    updateName(5, '✅');
  await advanceTime(250);

    updateName(3, '❌');

  await flushAllTimers();

  expect(getUsersNamesFromState(env)).toMatchInlineSnapshot(
    `['✅', '❌', '❌', '❌', '✅']`,
  );
  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: success ⋅ items: [1:User 1, 2:User 2, 3:User 3, 4:User 4, 5:User 5]
    -> status: success ⋅ items: [1:✅, 2:User 2, 3:User 3, 4:User 4, 5:User 5]
    -> status: success ⋅ items: [1:✅, 2:❌, 3:User 3, 4:User 4, 5:User 5]
    -> status: success ⋅ items: [1:✅, 2:❌, 3:✅, 4:User 4, 5:User 5]
    -> status: success ⋅ items: [1:✅, 2:❌, 3:✅, 4:❌, 5:User 5]
    -> status: success ⋅ items: [1:✅, 2:❌, 3:✅, 4:❌, 5:✅]
    -> status: success ⋅ items: [1:✅, 2:❌, 3:❌, 4:❌, 5:✅]
    -> status: refetching ⋅ items: [1:✅, 2:❌, 3:❌, 4:❌, 5:✅]
    -> status: success ⋅ items: [1:✅, 2:❌, 3:❌, 4:❌, 5:✅]
    "
  `);
});

test('query receives a RTU while the query is loading by the component mount', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    usesRealTimeUpdates: true,
    });

  const renders = createLoggerStore();

    renderHook(() => {
    const { data, status } = env.apiStore.useItem('users||2', {
        returnRefetchingStatus: true,
      });

      renders.add({ status, data });
    });

  await advanceTime(200);

  act(() => {
    env.serverTable.setItem(
      'users||2',
      { id: 2, name: '✅' },
      { triggerRTUEvent: true },
    );
    });

  await flushAllTimers();

  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: loading ⋅ data: null
    -> status: success ⋅ data: {id:2, name:✅}
    -> status: refetching ⋅ data: {id:2, name:✅}
    -> status: success ⋅ data: {id:2, name:✅}
    "
  `);
});

test('delete mutation with RTU', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users'] } },
    usesRealTimeUpdates: true,
  });

  const renders = createLoggerStore({
    arrays: 'all',
  });

  renderHook(() => {
    const { items, status } = env.apiStore.useListQuery(
      { tableId: 'users' },
      {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
        itemSelector(data) {
          return data.name;
        },
      },
    );

    renders.add({ status, items });
  });

  act(() => {
    void deleteItem(env, 'users', 2, {
      optimisticUpdate: true,
      duration: 600,
      triggerRTU: true,
    });
  });

  await flushAllTimers();

  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: success ⋅ items: [User 1, User 2, User 3, User 4, User 5]
    -> status: success ⋅ items: [User 1, User 3, User 4, User 5]
    -> status: refetching ⋅ items: [User 1, User 3, User 4, User 5]
    -> status: success ⋅ items: [User 1, User 3, User 4, User 5]
    "
  `);
});

test('creation mutation with RTU', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users'] } },
    usesRealTimeUpdates: true,
  });

  const renders = createLoggerStore({
    arrays: 'all',
  });

  renderHook(() => {
    const { items, status } = env.apiStore.useListQuery(
      { tableId: 'users' },
      {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
        itemSelector(data) {
          return data.name;
        },
      },
    );

    renders.add({ status, items });
  });

  act(() => {
    void addItemWithIdGeneratedByClient(env, 'users', '8', '🆕', {
      triggerRTU: true,
    });
  });

  await flushAllTimers();

  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: success ⋅ items: [User 1, User 2, User 3, User 4, User 5]
    -> status: refetching ⋅ items: [User 1, User 2, User 3, User 4, User 5]
    -> status: success ⋅ items: [User 1, User 2, User 3, User 4, User 5, 🆕]
    "
  `);
});

test('simple update mutation with RTU', async () => {
  const env = createListQueryStoreTestEnv(initialServerData, {
    testScenario: { loaded: { tables: ['users'] } },
    usesRealTimeUpdates: true,
  });

  const renders = createLoggerStore({
    arrays: 'all',
  });

  renderHook(() => {
    const { items, status } = env.apiStore.useListQuery(
      { tableId: 'users' },
      {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
        itemSelector(data) {
          return data.name;
        },
      },
    );

    renders.add({ status, items });
  });

  act(() => {
    void env.performClientItemUpdateAction(
      'users||5',
      { name: '🆕' },
      {
        triggerRTU: true,
      },
    );
  });

  await flushAllTimers();

  expect(renders.snapshot).toMatchInlineSnapshot(`
    "
    -> status: success ⋅ items: [User 1, User 2, User 3, User 4, User 5]
    -> status: refetching ⋅ items: [User 1, User 2, User 3, User 4, User 5]
    -> status: success ⋅ items: [User 1, User 2, User 3, User 4, 🆕]
    "
  `);
});

test.concurrent('RTU throttling', async () => {
  const env = createTestEnv({
    initialServerData,
    useLoadedSnapshot: { tables: ['users'] },
    emulateRTU: true,
    disableInitialDataInvalidation: true,
    dynamicRTUThrottleMs(lastDuration) {
      if (lastDuration < 100) {
        return 200;
      }

      return 300;
    },
  });

  const renders = createRenderStore();

  renderHook(() => {
    const { items, status } = env.store.useListQuery(
      { tableId: 'users' },
      {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
        itemSelector(data) {
          return data.name;
        },
      },
    );

    renders.add({ status, items });
  });

  const waitUntil = waitElapsedTime();

  env.serverMock.setFetchDuration(200);

  updateItemName(env, 'users', 5, '1', { duration: 100 });

  await waitUntil(350);

  env.serverMock.setFetchDuration(30);

  updateItemName(env, 'users', 5, '2', { duration: 100 });

  await waitUntil(670);

  updateItemName(env, 'users', 5, '3', { duration: 100 });

  await waitUntil(900);

  expect(
    env.serverMock.fetchs[1]!.time.start - env.serverMock.fetchs[0]!.time.end,
  ).toBeGreaterThanOrEqual(300);

  const diffLastFetch =
    env.serverMock.fetchs[2]!.time.start - env.serverMock.fetchs[1]!.time.end;

  expect(diffLastFetch).toBeGreaterThanOrEqual(200);
  expect(diffLastFetch).toBeLessThan(300);

  expect(renders.getSnapshot({ arrays: 'firstAndLast' }))
    .toMatchInlineSnapshotString(`
    "
    status: success -- items: [User 1, ...(3 between), User 5]
    status: refetching -- items: [User 1, ...(3 between), User 5]
    status: success -- items: [User 1, ...(3 between), 1]
    status: refetching -- items: [User 1, ...(3 between), 1]
    status: success -- items: [User 1, ...(3 between), 2]
    status: refetching -- items: [User 1, ...(3 between), 2]
    status: success -- items: [User 1, ...(3 between), 3]
    "
  `);
});

test.concurrent('mount component after a RTU', async () => {
  const env = createTestEnv({
    initialServerData,
    useLoadedSnapshot: { tables: ['users'] },
    emulateRTU: true,
    dynamicRTUThrottleMs(lastDuration) {
      if (lastDuration < 100) {
        return 200;
      }

      return 300;
    },
  });

  const renders = createRenderStore();

  env.serverMock.produceData((draft) => {
    draft['users']?.push({
      id: 6,
      name: 'User 6',
    });
  });

  await sleep(100);

  expect(env.store.store.state.queries).toMatchInlineSnapshotString(`
    {
      "{"tableId":"users"}": {
        "error": null,
        "hasMore": false,
        "items": [
          "users||1",
          "users||2",
          "users||3",
          "users||4",
          "users||5",
        ],
        "payload": {
          "tableId": "users",
        },
        "refetchOnMount": "realtimeUpdate",
        "status": "success",
        "wasLoaded": true,
      },
    }
  `);

  renderHook(() => {
    const { items, status } = env.store.useListQuery(
      { tableId: 'users' },
      {
        returnRefetchingStatus: true,
        disableRefetchOnMount: true,
        itemSelector(data) {
          return data.name;
        },
      },
    );

    renders.add({ status, items });
  });

  await env.serverMock.waitFetchIdle(0, 1500);

  expect(renders.getSnapshot({ arrays: 'all' })).toMatchInlineSnapshotString(`
    "
    status: success -- items: [User 1, User 2, User 3, User 4, User 5]
    status: refetching -- items: [User 1, User 2, User 3, User 4, User 5]
    status: success -- items: [User 1, User 2, User 3, User 4, User 5, User 6]
    "
  `);
});
